### ISSUE TITLE
How to prepare .rda file (reopen)

### ISSUE THREAD

**Issue by balajikalluri** [jMotif/jmotif-R#10]
I would like to prepare my dataset in the same format as CBF.rda for quick evaluation. Could you suggest any links on fields or steps etc.?

Thanks,
Bala

**Comment by seninp** [comment]
The code is not designed to use a specifically-formatted data. 

I use the list which has intuitively-named elements for the simplicity. The `.rda` data format is discussed in [the R manual](https://cran.r-project.org/doc/manuals/r-release/R-exts.html#Data-in-packages). Specifically in jmotif-R the dataset is build as shown in here https://github.com/jMotif/jmotif-R/blob/master/inst/site/makedata.R.

**Comment by balajikalluri** [comment]
Thanks for that piece of information. 

I quickly tried to read the source data files for both "Gun_Point" and "CBF" that I downloaded from UCR repo. 

To understand converting the above target datasets into .rda data files, I used your reference scripts in /makedata.R. But I receive error while creating the matrix...

> data_train = matrix(unlist(dtrain[,-1]), nrow = length(labels_train))
> Error in matrix(unlist(dtrain[, -1]), nrow = length(labels_train)) : 
>   'data' must be of a vector type, was 'NULL'
> data_test = matrix(unlist(dtest[,-1]), nrow = length(labels_test))
> Error in matrix(unlist(dtest[, -1]), nrow = length(labels_test)) : 
>   'data' must be of a vector type, was 'NULL'

Pls. advice...

-Bala
