### ISSUE TITLE
How to prepare .rda file (reopen)

### ISSUE THREAD

**Issue by balajikalluri** [jMotif/jmotif-R#11]
Thanks for that piece of information. That was very useful.

I quickly tried to read the source data files for both "Gun_Point" and "CBF" that I downloaded from UCR repo. 

To understand converting the above target datasets into .rda data files, I used your reference scripts in /makedata.R. But I receive error while creating the matrix...

> data_train = matrix(unlist(dtrain[,-1]), nrow = length(labels_train))
> Error in matrix(unlist(dtrain[, -1]), nrow = length(labels_train)) : 
>   'data' must be of a vector type, was 'NULL'
> data_test = matrix(unlist(dtest[,-1]), nrow = length(labels_test))
> Error in matrix(unlist(dtest[, -1]), nrow = length(labels_test)) : 
>   'data' must be of a vector type, was 'NULL'

Pls. advice...

-Bala

PS: MY friend, may I also request that you don't immediately close the issue thread, by doing that it doesn't allow me to raise reissue on the same thread again.

**Comment by seninp** [comment]
As I have mentioned before, I can't and wouldn't debug issues on the remote systems not related
to the code, since I am not getting paid for my time. Most of your questions are trivial and show the lack of effort -- I would suggest you to spend more time understanding the algorithms, code, and specifically why things fail.

On Wed, Dec 16, 2015 at 10:21 AM, K M Balaji notifications@github.com
wrote:

> Thanks for that piece of information That was very useful
> 
> I quickly tried to read the source data files for both "Gun_Point" and
> "CBF" that I downloaded from UCR repo
> 
> To understand converting the above target datasets into rda data files, I
> used your reference scripts in /makedataR But I receive error while
> creating the matrix
> 
> data_train = matrix(unlist(dtrain[,-1]), nrow = length(labels_train))
> Error in matrix(unlist(dtrain[, -1]), nrow = length(labels_train)) :
> 'data' must be of a vector type, was 'NULL'
> data_test = matrix(unlist(dtest[,-1]), nrow = length(labels_test))
> Error in matrix(unlist(dtest[, -1]), nrow = length(labels_test)) :
> 'data' must be of a vector type, was 'NULL'
> 
> Pls advice
> 
> -Bala
> 
> PS: MY friend, may I also request that you don't immediately close the
> issue thread, by doing that it doesn't allow me to raise reissue on the
> same thread again
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/jMotif/jmotif-R/issues/11.

## 

Mahalo, Pavel.
