### ISSUE TITLE
Installation issue - error: 'unordered_map' in namespace 'std' does not name a type

### ISSUE THREAD

**Issue by vdakshin** [jMotif/jmotif-R#27]
Hi - I am trying to install on Windows 7 under R 3.2.3. I get the following error:

> library(devtools)
> install_github('jMotif/jmotif-R')
> Downloading GitHub repo jMotif/jmotif-R@master
> from URL https://api.github.com/repos/jMotif/jmotif-R/zipball/master
> Installing jmotif
> "C:/PROGRA~1/R/R-32~1.3/bin/x64/R" --no-site-file --no-environ --no-save  \
>   --no-restore CMD INSTALL  \
>   "C:/Users/T897551/AppData/Local/Temp/Rtmpofu5I3/devtools2c0c144c27e0/jMotif-jmotif-R-c948d79"  \
>   --library="C:/Program Files/R/R-3.2.3/library" --install-tests 
- installing _source_ package 'jmotif' ...
  *\* libs

**\* arch - i386
g++ -m32 -std=c++0x -I"C:/PROGRA~1/R/R-32~1.3/include" -DNDEBUG -I"../inst/include/"   -I"C:/Program Files/R/R-3.2.3/library/Rcpp/include" -I"C:/Program Files/R/R-3.2.3/library/RcppArmadillo/include" -I"d:/RCompile/r-compiling/local/local323/include"     -O2 -Wall  -mtune=core2 -c RcppExports.cpp -o RcppExports.o
In file included from C:/Program Files/R/R-3.2.3/library/RcppArmadillo/include/armadillo:50:0,
                 from C:/Program Files/R/R-3.2.3/library/RcppArmadillo/include/RcppArmadilloForward.h:46,
                 from C:/Program Files/R/R-3.2.3/library/RcppArmadillo/include/RcppArmadillo.h:31,
                 from ../inst/include/jmotif.h:4,
                 from RcppExports.cpp:4:
C:/Program Files/R/R-3.2.3/library/RcppArmadillo/include/armadillo_bits/compiler_setup.hpp:209:111: note: #pragma message: WARNING: compiler is in C++11 mode, but it has incomplete support for C++11 features;
C:/Program Files/R/R-3.2.3/library/RcppArmadillo/include/armadillo_bits/compiler_setup.hpp:210:87: note: #pragma message: WARNING: if something breaks, you get to keep all the pieces.
C:/Program Files/R/R-3.2.3/library/RcppArmadillo/include/armadillo_bits/compiler_setup.hpp:211:93: note: #pragma message: WARNING: to forcefully prevent Armadillo from using C++11 features,
C:/Program Files/R/R-3.2.3/library/RcppArmadillo/include/armadillo_bits/compiler_setup.hpp:212:90: note: #pragma message: WARNING: #define ARMA_DONT_USE_CXX11 before #include <armadillo>
In file included from RcppExports.cpp:4:0:
../inst/include/jmotif.h:213:1: error: 'unordered_map' in namespace 'std' does not name a type
make: **\* [RcppExports.o] Error 1
Warning: running command 'make -f "Makevars" -f "C:/PROGRA~1/R/R-32~1.3/etc/i386/Makeconf" -f "C:/PROGRA~1/R/R-32~1.3/share/make/winshlib.mk" CXX='$(CXX1X) $(CXX1XSTD)' CXXFLAGS='$(CXX1XFLAGS)' CXXPICFLAGS='$(CXX1XPICFLAGS)' SHLIB_LDFLAGS='$(SHLIB_CXX1XLDFLAGS)' SHLIB_LD='$(SHLIB_CXX1XLD)' SHLIB="jmotif.dll" OBJECTS="RcppExports.o discord.o distance.o hot-sax.o jmotif.o paa.o repair.o rra.o sax-vsm.o sax.o string.o utils.o visit_registry.o znorm.o"' had status 2
ERROR: compilation failed for package 'jmotif'
- removing 'C:/Program Files/R/R-3.2.3/library/jmotif'
  Error: Command failed (1)

It seems like a namespace error. Any pointers would be appreciated.

Thanks.

**Comment by seninp** [comment]
Hi there: I think this is a compiler error. If you are installing from the
current trunk, try to use more up-to-date compiler, or use the older
(release) version. I'll look at the issue tonight -- if it is reproducible
on my own workstation. Sorry!

On Tue, Feb 16, 2016 at 1:51 PM, vdakshin notifications@github.com wrote:

> Hi - I am trying to install on Windows 7 under R 3.2.3. I get the
> following error:
> 
> library(devtools)
> install_github('jMotif/jmotif-R')
> Downloading GitHub repo jMotif/jmotif-R@master
> from URL https://api.github.com/repos/jMotif/jmotif-R/zipball/master
> Installing jmotif
> "C:/PROGRA~1/R/R-32~1.3/bin/x64/R" --no-site-file --no-environ --no-save \
> --no-restore CMD INSTALL \
> "C:/Users/T897551/AppData/Local/Temp/Rtmpofu5I3/devtools2c0c144c27e0/jMotif-jmotif-R-c948d79"
> \
> --library="C:/Program Files/R/R-3.2.3/library" --install-tests
> - installing _source_ package 'jmotif' ... *\* libs
> 
> **\* arch - i386
> g++ -m32 -std=c++0x -I"C:/PROGRA~1/R/R-32~1.3/include" -DNDEBUG
> -I"../inst/include/" -I"C:/Program Files/R/R-3.2.3/library/Rcpp/include"
> -I"C:/Program Files/R/R-3.2.3/library/RcppArmadillo/include"
> -I"d:/RCompile/r-compiling/local/local323/include" -O2 -Wall -mtune=core2
> -c RcppExports.cpp -o RcppExports.o
> In file included from C:/Program
> Files/R/R-3.2.3/library/RcppArmadillo/include/armadillo:50:0,
> from C:/Program
> Files/R/R-3.2.3/library/RcppArmadillo/include/RcppArmadilloForward.h:46,
> from C:/Program
> Files/R/R-3.2.3/library/RcppArmadillo/include/RcppArmadillo.h:31,
> from ../inst/include/jmotif.h:4,
> from RcppExports.cpp:4:
> C:/Program
> Files/R/R-3.2.3/library/RcppArmadillo/include/armadillo_bits/compiler_setup.hpp:209:111:
> note: #pragma message: WARNING: compiler is in C++11 mode, but it has
> incomplete support for C++11 features;
> C:/Program
> Files/R/R-3.2.3/library/RcppArmadillo/include/armadillo_bits/compiler_setup.hpp:210:87:
> note: #pragma message: WARNING: if something breaks, you get to keep all
> the pieces.
> C:/Program
> Files/R/R-3.2.3/library/RcppArmadillo/include/armadillo_bits/compiler_setup.hpp:211:93:
> note: #pragma message: WARNING: to forcefully prevent Armadillo from using
> C++11 features,
> C:/Program
> Files/R/R-3.2.3/library/RcppArmadillo/include/armadillo_bits/compiler_setup.hpp:212:90:
> note: #pragma message: WARNING: #define ARMA_DONT_USE_CXX11 before #include
> In file included from RcppExports.cpp:4:0:
> ../inst/include/jmotif.h:213:1: error: 'unordered_map' in namespace 'std'
> does not name a type
> make: **\* [RcppExports.o] Error 1
> Warning: running command 'make -f "Makevars" -f
> "C:/PROGRA~1/R/R-32~1.3/etc/i386/Makeconf" -f
> "C:/PROGRA~1/R/R-32~1.3/share/make/winshlib.mk" CXX='$(CXX1X)
> $(CXX1XSTD)' CXXFLAGS='$(CXX1XFLAGS)' CXXPICFLAGS='$(CXX1XPICFLAGS)'
> SHLIB_LDFLAGS='$(SHLIB_CXX1XLDFLAGS)' SHLIB_LD='$(SHLIB_CXX1XLD)'
> SHLIB="jmotif.dll" OBJECTS="RcppExports.o discord.o distance.o hot-sax.o
> jmotif.o paa.o repair.o rra.o sax-vsm.o sax.o string.o utils.o
> visit_registry.o znorm.o"' had status 2
> ERROR: compilation failed for package 'jmotif'
> - removing 'C:/Program Files/R/R-3.2.3/library/jmotif' Error: Command
>   failed (1)
> 
> It seems like a namespace error. Any pointers would be appreciated.
> 
> Thanks.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/jMotif/jmotif-R/issues/27.

## 

Mahalo, Pavel.

**Comment by vdakshin** [comment]
Hi - Thanks. I have tried with Rtools version 3.2 as well as 3.3 but still get the same error on both. How can I change the -std option with the compiler? When you say use the older (release) version do you mean the compiler or the jmotif version?

**Comment by seninp** [comment]
At my workstation I use the following, which builds with no issues:

$ gcc --version

Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr
--with-gxx-include-dir=/usr/include/c++/4.2.1

Apple LLVM version 7.0.2 (clang-700.1.81)

Target: x86_64-apple-darwin15.3.0

Thread model: posix

Also on Travis it builds with no issues too, see here:
https://travis-ci.org/jMotif/jmotif-R

I think this is a gcc version error, because unsorted map only appears in
after versions, which one do you use?

On Tue, Feb 16, 2016 at 7:44 PM, vdakshin notifications@github.com wrote:

> Hi - Thanks. I have tried with Rtools version 3.2 as well as 3.3 but still
> get the same error on both. How can I change the -std option with the
> compiler? When you say use the older (release) version do you mean the
> compiler or the jmotif version?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/jMotif/jmotif-R/issues/27#issuecomment-184984908.

## 

Mahalo, Pavel.
