### ISSUE TITLE
Installation Issues

### ISSUE THREAD

**Issue by BoJanisch** [jMotif/jmotif-R#3]
Hi seninp,

I'm going through your ReadMe and I'm getting error when grabbing the Github repository: 

install_github('jMotif/jmotif-R')
Downloading GitHub repo jMotif/jmotif-R@master
Installing jmotif
"C:/PROGRA~1/R/R-32~1.2/bin/x64/R" --no-site-file --no-environ --no-save --no-restore CMD INSTALL  \ "C:/Users/NotUrPC/AppData/Local/Temp/RtmpamNSTe/devtoolsbf46db12781/jMotif-jmotif-R-f2ecb5c" --library="C:/Program  \ Files/R/R-3.2.2/library" --install-tests 
_installing *source_ package 'jmotif' ...
*\* libs

**\* arch - i386
g++ -m32 -I"C:/PROGRA~1/R/R-32~1.2/include" -DNDEBUG    -I"C:/Program Files/R/R-3.2.2/library/Rcpp/include" -I"d:/RCompile/r-compiling/local/local320/include"     -O2 -Wall  -mtune=core2 -c RcppExports.cpp -o RcppExports.o 

g++ -m32 -I"C:/PROGRA~1/R/R-32~1.2/include" -DNDEBUG    -I"C:/Program Files/R/R-3.2.2/library/Rcpp/include" -I"d:/RCompile/r-compiling/local/local320/include"     -O2 -Wall  -mtune=core2 -c jmotif.cpp -o jmotif.o
jmotif.cpp: In function 'bool is_equal_mindist(Rcpp::CharacterVector, Rcpp::CharacterVector)':
jmotif.cpp:295:30: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
jmotif.cpp: In function 'std::map<int, Rcpp::Vector<16> > sax_by_chunking(Rcpp::NumericVector, int, int, double)':
jmotif.cpp:396:34: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
jmotif.cpp: In function 'Rcpp::DataFrame bags_to_tfidf(Rcpp::List)':
jmotif.cpp:583:38: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
jmotif.cpp:594:35: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
jmotif.cpp:627:34: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
jmotif.cpp:632:40: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
jmotif.cpp:646:34: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
jmotif.cpp:663:34: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
jmotif.cpp:668:40: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
jmotif.cpp:679:34: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
jmotif.cpp:699:34: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
jmotif.cpp:706:34: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
jmotif.cpp: In function 'Rcpp::DataFrame cosine_sim(Rcpp::List)':
jmotif.cpp:742:33: warning: comparison between signed and unsigned integer expressions [-Wsign-
compare]
jmotif.cpp:766:35: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
jmotif.cpp:782:37: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
jmotif.cpp: In function 'discord_record find_best_discord_brute_force(const NumericVector&, int, VisitRegistry_)':
jmotif.cpp:960:26: error: 'isnan' was not declared in this scope
jmotif.cpp:960:26: note: suggested alternative:
c:\rbuildtools\3.2\gcc-4.6.3\bin../lib/gcc/i686-w64-mingw32/4.6.3/../../../../include/c++/4.6.3/cmath:768:5: note:   'std::isnan'
make: *_\* [jmotif.o] Error 1
Warnung: Ausführung von Kommando 'make -f "C:/PROGRA~1/R/R-32~1.2/etc/i386/Makeconf" -f "C:/PROGRA~1/R/R-32~1.2/share/make/winshlib.mk" SHLIB_LDFLAGS='$(SHLIB_CXXLDFLAGS)' SHLIB_LD='$(SHLIB_CXXLD)' SHLIB="jmotif.dll" OBJECTS="RcppExports.o jmotif.o"' ergab Status 2
ERROR: compilation failed for package 'jmotif'
*removing 'C:/Program Files/R/R-3.2.2/library/jmotif'
Error: Command failed (1)

Do you know where the error could be? I've followed your guide step by step and got no other problems. I'm running R on Windows 7 x64. If you need further information, feel free to ask. 

Best regards
BoJanisch

**Comment by seninp** [comment]
Hi: Thank you for the report! It's a namespaces issue, i guess. Will fix now.
