### ISSUE TITLE
about the sliding window length in testthat

### ISSUE THREAD

**Issue by rogerchen1226** [jMotif/jmotif-R#4]
I saw the paper then confused about the sliding window size, it always +1 and I tried to test the testthat about the sax_via_window.R ,then i got some error about testthat.

There is a problem about that +1 is correct?
length(sax1)=54, length(t(dat))=60,slidingwindowsize=6
54=60-6+1

`sax1 <- sax_via_window(t(dat), 6, 3, 3, "none", 0.01)`
`expect_equal(length(sax1), length(t(dat)) - 6 + 1)`

`Error: Test failed: 'SAX test #1'`
`Not expected: length(sax1) not equal to length(t(dat)) - 6 + 1`
`55 - 54 == 1.`

Thanks.
Roger

**Comment by seninp** [comment]
Hi Roger: There was a problem with a single point shift, I thought that it is gone. Did you install the latest trunk or used the CRAN version?

```
> dat <- read.table(textConnection(
+ gsub("\n", " ", "0 0 0 0 0 -0.270340178359072 -0.367828308500142 0.666980581124872 1.87088147328446
+ 2.14548907684624 -0.480859313143032 -0.72911654245842 -0.490308602315934 -0.66152028906509
+ -0.221049033806403 0.367003418871239 0.631073992586373 0.0487728723414486 0.762655178750436
+ 0.78574757843331 0.338239686422963 0.784206454089066 -2.14265084073625 2.11325193044223
+ 0.186018356196443 0 0 0 0 0 0 0 0 0 0 0.519132472499234 -2.604783141655
+ -0.244519550114012 -1.6570790528784 3.34184602886343 2.10361226260999 1.9796808733979
+ -0.822247322003058 1.06850578033292 -0.678811824405992 0.804225748913681 0.57363964388698
+ 0.437113583759113 0.437208643628268 0.989892093383503 1.76545983424176 0.119483882364649
+ -0.222311941138971 -0.74669456611669 -0.0663660879732063 0 0 0 0 0")
+ ), as.is = T)
> sax1 <- sax_via_window(t(dat), 6, 3, 3, "none", 0.01)
> str(sax1)
List of 55
 $ 0 : chr "bba"
 $ 1 : chr "cca"
...
```

**Comment by rogerchen1226** [comment]
Thanks a lot, it working!
I thought that maybe it cause my version is 3.1.3.
Thank you again!

**Comment by seninp** [comment]
You are welcome! I am quite new to RCpp, and there is some discrepancy between R and C++ in indexing -- 1-based or 0-based, so bugs happen.
