### ISSUE TITLE
Problems while installing the package

### ISSUE THREAD

**Issue by Duwaraka** [jMotif/jmotif-R#5]
While installing the package ('jMotif/jmotif-R'), i got the following error

C:/PROGRA~1/R/R-32~1.2/etc/i386/Makeconf:189: recipe for target 'RcppExports.o' failed
make: **\* [RcppExports.o] Error 1
Warning: running command 'make -f "C:/PROGRA~1/R/R-32~1.2/etc/i386/Makeconf" -f "C:/PROGRA~1/R/R-32~1.2/share/make/winshlib.mk" SHLIB_LDFLAGS='$(SHLIB_CXXLDFLAGS)' SHLIB_LD='$(SHLIB_CXXLD)' SHLIB="jmotif.dll" OBJECTS="RcppExports.o jmotif.o"' had status 2
ERROR: compilation failed for package 'jmotif'
- removing 'C:/Users/bdgmasu/Documents/R/win-library/3.2/jmotif'

and the installation terminates.

Please Help

**Comment by seninp** [comment]
Hi: I am sorry, I don't have any windows workstation to test the package build or enough knowledge to debug the issue. However, upon the CRAN submission the built was tested by CRAN on windows and mac (i work on linux) and all checks [were successful](https://cran.r-project.org/web/checks/check_results_jmotif.html). If you build any other Rcpp package, does the error occur?
