### ISSUE TITLE
Error in executing znorm function

### ISSUE THREAD

**Issue by balajikalluri** [jMotif/jmotif-R#6]
Hi Senin,

I'm getting some errors when running the jMotif-R source codes in steps..
Error happens when I try to run the following line in my R-console on windows.

> lines(x, znorm(y, 0.01), type="l", col="red")
> Error in xy.coords(x, y) : could not find function "znorm"

I have successfully installed both devtools & jMotif-R package using commands you listed prior to this.

Any idea???

Thanks,
Bala

**Comment by seninp** [comment]
Did you load the lib with 

```
library(jmotif)
```
