### ISSUE TITLE
Error reproducing heatmap i.e. plot the weighted patterns

### ISSUE THREAD

**Issue by balajikalluri** [jMotif/jmotif-R#7]
Hi Senin,

Thanks. You pointed me to the missing link to load jmotif package before. 

I continued on with the demo and everything was fine until I reached a point to plot weighted patterns on the time series.

I get the following error when I try to load library(scales) for whatever reasons, though library(ggplot2) loaded well.

> library(scales)
> Error in library(scales) : there is no package called ‘scales’

Any idea???

Regards,
Bala

**Comment by seninp** [comment]
you've got to install the library 'scales'?

**Comment by balajikalluri** [comment]
Yes I did that...still I receive the same error when I load the library....weird !!!

**Comment by balajikalluri** [comment]
> install.packages("scales")
> Installing package into ‘C:/Users/Balaji/Documents/R/win-library/3.2’
> (as ‘lib’ is unspecified)
> trying URL 'https://cran.uni-muenster.de/bin/windows/contrib/3.2/scales_0.3.0.zip'
> Content type 'application/zip' length 605174 bytes (590 KB)
> downloaded 590 KB

package ‘scales’ successfully unpacked and MD5 sums checked
Warning: cannot remove prior installation of package ‘scales’

The downloaded binary packages are in
        C:\Users\Balaji\AppData\Local\Temp\RtmpKged6V\downloaded_packages

> library(scales)
> Error in library(scales) : there is no package called ‘scales’
