### ISSUE TITLE
Error still in loading library 'scales'

### ISSUE THREAD

**Issue by balajikalluri** [jMotif/jmotif-R#8]
Hi Senin,

Sorry, I tried also installing "scales" package as shown below and then loaded the libraries within but still it fails....

```
install.packages("scales")
Installing package into ‘C:/Users/Balaji/Documents/R/win-library/3.2’
(as ‘lib’ is unspecified)
trying URL 'https://cran.uni-muenster.de/bin/windows/contrib/3.2/scales_0.3.0.zip'
Content type 'application/zip' length 605174 bytes (590 KB)
downloaded 590 KB
```

package ‘scales’ successfully unpacked and MD5 sums checked
Warning: cannot remove prior installation of package ‘scales’

The downloaded binary packages are in
C:\Users\Balaji\AppData\Local\Temp\RtmpKged6V\downloaded_packages

```
library(scales)
Error in library(scales) : there is no package called ‘scales’
```

Any clue....

Regards,
Bala

**Comment by seninp** [comment]
Sorry, to hear that. I can't spare time for that now. Try to use some other way to visualize things, maybe try to install or login into linux. I don't have windows.
