### ISSUE TITLE
Pls help selecting optimal sliding window (w), PAA size (p) & alphabet size (a) in jmotif-R 

### ISSUE THREAD

**Issue by balajikalluri** [jMotif/jmotif-R#9]
Hello my friend,

You have explained in your sax-vsm classic (Java) implementation tutorial page, the implementation of  "Running the parameter sampler (Optimizer)". I would like to know if the same has also been implemented in R-equivalent of jMotif package?

If yes, a pointer to demonstrate how to run this...
*_sliding window range as [10-150], PAA size as [5-75], and the alphabet [2-18] *_
and what to expect as output of the function will be very helpful. 

My energy dataset also has multiple signatures, each of whose subsequences are of varied lengths within time series. And goal is to use DiRect sampler that you employed to find the optimal set of parameters prior to classification.

Thanks in anticipation.

Best regards,
Bala

**Comment by seninp** [comment]
Direct optimization is not a part of this project. Please use our Java
implementation. Thanks!

On Mon, Dec 14, 2015 at 5:13 PM, K M Balaji notifications@github.com
wrote:

> Hello my friend,
> 
> You have explained in your sax-vsm classic (Java) implementation tutorial
> page, the implementation of "Running the parameter sampler (Optimizer)" I
> would like to know if the same has also been implemented in R-equivalent of
> jMotif package?
> 
> If yes, a pointer to demonstrate the how to run this
> *_sliding window range as [10-150], PAA size as [5-75], and the alphabet
> [2-18] *_
> and what to expect as output of the function will be helpful
> 
> My energy dataset also has multiple signatures, each of whose subsequences
> are of varied lengths within time series And goal is to use DiRect sampler
> that you employed to find the optimal set of parameters prior to
> classification
> 
> Thanks in anticipation
> 
> Best regards,
> Bala
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/jMotif/jmotif-R/issues/9.

## 

Mahalo, Pavel.

**Comment by balajikalluri** [comment]
Ok. Thanks for clarifying. 

Could you pls suggest any good reference to understanding Direct optimization in the context of SAX parameter selection i.e. w, p & a. ?

-Bala

**Comment by seninp** [comment]
All relevant citations are in our 2013 paper about SAX-VSM. This repository
concerns jmotif-R project -- if there is no issues with the code -- please,
use other channels to get the information. Thanks!

On Mon, Dec 14, 2015 at 6:02 PM, K M Balaji notifications@github.com
wrote:

> Ok. Thanks for clarifying.
> 
> Could you pls suggest any good reference to understanding Direct
> optimization in the context of SAX parameter selection i.e. w, p & a. ?
> 
> -Bala
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/jMotif/jmotif-R/issues/9#issuecomment-164495312.

## 

Mahalo, Pavel.

**Comment by seninp** [comment]
I've just updated README with an example for the parameters optimization. While not the optimal process, it works and might be useful for you. Thanks!

**Comment by balajikalluri** [comment]
The script for parameter optimization is quite useful. I was able to successfully run it with CBF example case.

Thanks,
Bala

**Comment by balajikalluri** [comment]
Hi Senin,
I was trying to run through and understand your CV optimization script for SAX parameter selection. 
I was not clear with the logic that you employed as the function to be optimized (i.e. cross validation error function) as the second step. 

I'm able to understand the following:

1) Goal: Is to identify the best/optimum sets of SAX parameters (i.e. w, p & a) within certain bounds of values described using c(10,2,2) and c(120,60,12) give the time-series dataset with labels for each class. 

2) You define a "cross-validation error" function on which the DIRECTL() optimization algorithm works with each set of SAX parameters iteratively. 

3) At each iteration, DIRECTL() algo estimates the corresponding the mean cverror in classifying the symbolized subsequences for each time series in the input dataset. 

4) Finally, the optimum choice of set of SAX parameters(w,p & a) is chosen to be the one for which cverror is zero (i.e. classification is 100% correct) 

Therefore, based on these points my understanding is that "cross-validation error" function that you have implemented is basically a trying to essentially again using cosine similarity as metric to compute the error based on tf-idf matrix. 

Am I correct in saying this? (Sorry I'd to communicate through a long message here....) 

Kindly acknowledge.

Thanks,
Bala

**Comment by seninp** [comment]
Sorry, what is the exact question -- is that the CV function definition?
What is that not clear in there?

On Fri, Dec 18, 2015 at 11:27 AM, K M Balaji notifications@github.com
wrote:

> Hi Senin,
> I was trying to run through and understand your CV optimization script for
> SAX parameter selection.
> I was not clear with the logic that you employed as the function to be
> optimized (i.e. cross validation error function) as the second step.
> 
> I'm able to understand the following:
> 
> 1) Goal: Is to identify the best/optimum sets of SAX parameters (i.e. w, p
> & a) within certain bounds of values described using c(10,2,2) and
> c(120,60,12) give the time-series dataset with labels for each class.
> 
> 2) You define a "cross-validation error" function on which the DIRECTL()
> optimization algorithm works with each set of SAX parameters iteratively.
> 
> 3) At each iteration, DIRECTL() algo estimates the corresponding the mean
> cverror in classifying the symbolized subsequences for each time series in
> the input dataset.
> 
> 4) Finally, the optimum choice of set of SAX parameters(w,p & a) is chosen
> to be the one for which cverror is zero (i.e. classification is 100%
> correct)
> 
> Therefore, based on these points my understanding is that
> "cross-validation error" function that you have implemented is basically a
> trying to essentially again using cosine similarity as metric to compute
> the error based on tf-idf matrix.
> 
> Am I correct in saying this? (Sorry I'd to communicate through a long
> message here....)
> 
> Kindly acknowledge.
> 
> Thanks,
> Bala
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/jMotif/jmotif-R/issues/9#issuecomment-165741775.

## 

Mahalo, Pavel.

**Comment by balajikalluri** [comment]
I just want to make sure my understanding on how CV function works in determining the optimum SAX parameters i.e. sliding window size(w), PAA size(p) and alphabet size(a)?

Hence, based on your code I tried to summarize them in steps which I need to crosscheck with you.

That's it.

**Comment by seninp** [comment]
Sorry, CV works the way, I believe, it should. Thanks!

On Fri, Dec 18, 2015 at 3:39 PM, K M Balaji notifications@github.com
wrote:

> I just want to make sure my understanding on how CV function works in
> determining the optimum SAX parameters i.e. sliding window size(w), PAA
> size(p) and alphabet size(a)?
> 
> Hence, based on your code I tried to summarize them in steps which I need
> to crosscheck with you.
> 
> That's it.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/jMotif/jmotif-R/issues/9#issuecomment-165792526.

## 

Mahalo, Pavel.
